### Practice Questions for numpy

1. Define two custom numpy arrays, say A and B. Generate two new numpy arrays by stacking A and B vertically and horizontally.

In [24]:
import numpy as np
# define A
A = np.array([[1, 2, 3], [4, 5, 6]])
# define B
B = np.array([[6, 7, 8], [9, 10, 11]])
# vertically stack
new_grid = np.vstack((A, B))
new_grid

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [25]:
# horizontally stack
new_grid_1 = np.hstack((A, B))
new_grid_1

array([[ 1,  2,  3,  6,  7,  8],
       [ 4,  5,  6,  9, 10, 11]])

2. Find common elements between A and B. [Hint : Intersection of two sets]

In [26]:
common_elements = np.intersect1d(A, B)
common_elements

array([6])

3. Extract all numbers from A which are within a specific range. eg between 5 and 10. [Hint: np.where() might be useful or boolean masks]

In [29]:
# Use np.where to extract elements within the specified range (5 to 10 inclusive)
extract_A = A[np.where((5 <= A) & (A <= 10))]
extract_A

array([5, 6])

4. Filter the rows of iris_2d that has petallength (3rd column) > 1.5 and sepallength (1st column) < 5.0
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

In [31]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
filtered_rows = iris_2d[(iris_2d[:, 2] > 1.5) & (iris_2d[:, 0] < 5.0)]

print(filtered_rows)

[[4.8 3.4 1.6 0.2]
 [4.8 3.4 1.9 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [4.9 2.4 3.3 1. ]
 [4.9 2.5 4.5 1.7]]


### Practice Questions for Pandas
1. From df filter the 'Manufacturer', 'Model' and 'Type' for every 20th row starting from 1st (row 0).
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

In [33]:
import pandas as pd
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
filtered_df = df.loc[::20, ['Manufacturer', 'Model', 'Type']]
filtered_df

Manufacturer    Model     Type
0         Acura  Integra    Small
20     Chrysler  LeBaron  Compact
40        Honda  Prelude   Sporty
60      Mercury   Cougar  Midsize
80       Subaru   Loyale    Small

2. Replace missing values in Min.Price and Max.Price columns with their respective mean.
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

In [34]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
# Replace missing values in 'Min.Price' with its mean
df['Min.Price'].fillna(df['Min.Price'].mean(), inplace=True)

# Replace missing values in 'Max.Price' with its mean
df['Max.Price'].fillna(df['Max.Price'].mean(), inplace=True)

3. How to get the rows of a dataframe with row sum > 100?
df = pd.DataFrame(np.random.randint(10, 40, 60).reshape(-1, 4))

In [36]:
df = pd.DataFrame(np.random.randint(10, 40, 60).reshape(-1, 4))
# which means sum row
row_sums = df.sum(axis=1)
df_new = df[row_sums > 100]
df_new

0   1   2   3
0   33  38  13  19
2   36  37  38  39
3   32  27  25  23
4   22  30  37  19
6   30  22  35  27
8   37  29  22  37
9   15  26  29  33
10  12  25  38  29
12  18  31  26  32
14  21  19  32  39